export const queryKeys = {
  projects: ['projects'] as const,
  activeProject: ['projects', 'active'] as const,
  sessions: ['sessions'] as const,
  session: (id: string) => ['sessions', id] as const,
  files: ['files'] as const,
  fileContent: (path: string) => ['files', 'content', path] as const,
  templates: ['templates'] as const,
  settings: ['settings'] as const,
  health: ['health'] as const,
  mcp: ['mcp'] as const,
  skills: ['skills'] as const,
  knowledge: ['knowledge'] as const,
  browse: (path?: string) => ['browse', path ?? '~'] as const,
  projectValidation: (path: string) => ['projects', 'validation', path] as const,
  gitStatus: ['git', 'status'] as const,
  gitChangedFiles: ['git', 'changedFiles'] as const,
  gitHistory: ['git', 'history'] as const,
  gitBranches: ['git', 'versions'] as const,
  gitSyncStatus: ['git', 'syncStatus'] as const,
  gitConflicts: ['git', 'conflicts'] as const,
  nodeInstallations: ['runner', 'nodeInstallations'] as const,
}
