import type { editor } from "monaco-editor";

type IStandaloneThemeData = editor.IStandaloneThemeData;

/**
 * GitHub Dark theme — sourced from monaco-themes (TextMate-based).
 * Full VS Code-quality syntax highlighting with real token rules.
 *
 * Editor chrome colors are overridden to blend with our app's design tokens.
 */
export const darkTheme: IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", background: "121212", foreground: "e1e4e8" },
    { token: "comment", foreground: "959da5" },
    { token: "punctuation.definition.comment", foreground: "959da5" },
    { token: "string.comment", foreground: "959da5" },

    { token: "constant", foreground: "c8e1ff" },
    { token: "constant.language", foreground: "79b8ff" },
    { token: "constant.numeric", foreground: "79b8ff" },
    { token: "constant.character", foreground: "79b8ff" },
    { token: "entity.name.constant", foreground: "c8e1ff" },
    { token: "variable.other.constant", foreground: "c8e1ff" },
    { token: "variable.language", foreground: "c8e1ff" },

    { token: "entity", foreground: "b392f0" },
    { token: "entity.name", foreground: "b392f0" },
    { token: "entity.name.function", foreground: "b392f0" },
    { token: "entity.name.tag", foreground: "85e89d" },
    { token: "entity.name.type", foreground: "b392f0" },
    { token: "entity.name.class", foreground: "b392f0" },
    { token: "entity.other.attribute-name", foreground: "b392f0" },
    { token: "entity.other.inherited-class", foreground: "85e89d" },

    { token: "variable.parameter.function", foreground: "e1e4e8" },
    { token: "variable", foreground: "e1e4e8" },
    { token: "variable.other", foreground: "e1e4e8" },

    { token: "keyword", foreground: "f97583" },
    { token: "keyword.control", foreground: "f97583" },
    { token: "keyword.operator", foreground: "f97583" },
    { token: "keyword.other", foreground: "f97583" },
    { token: "storage", foreground: "f97583" },
    { token: "storage.type", foreground: "f97583" },
    { token: "storage.modifier", foreground: "f97583" },

    { token: "string", foreground: "9ecbff" },
    { token: "string.regexp", foreground: "dbedff" },
    { token: "string.escape", foreground: "c8e1ff" },

    { token: "support", foreground: "c8e1ff" },
    { token: "support.function", foreground: "c8e1ff" },
    { token: "support.class", foreground: "c8e1ff" },
    { token: "support.type", foreground: "79b8ff" },
    { token: "support.constant", foreground: "c8e1ff" },
    { token: "support.variable", foreground: "c8e1ff" },

    { token: "meta.property-name", foreground: "79b8ff" },

    { token: "invalid.broken", foreground: "fdaeb7", fontStyle: "italic" },
    { token: "invalid.deprecated", foreground: "fdaeb7", fontStyle: "italic" },
    { token: "invalid.illegal", foreground: "fdaeb7", fontStyle: "italic" },
    {
      token: "invalid.unimplemented",
      foreground: "fdaeb7",
      fontStyle: "italic",
    },

    { token: "markup.heading", foreground: "79b8ff", fontStyle: "bold" },
    { token: "markup.bold", fontStyle: "bold" },
    { token: "markup.italic", fontStyle: "italic" },
    { token: "markup.inserted", foreground: "85e89d" },
    { token: "markup.deleted", foreground: "fdaeb7" },
    { token: "markup.changed", foreground: "ffab70" },
    { token: "markup.inline.raw", foreground: "9ecbff" },

    { token: "punctuation.definition.tag", foreground: "85e89d" },

    // Monaco-specific tokens
    { token: "number", foreground: "79b8ff" },
    { token: "number.hex", foreground: "79b8ff" },
    { token: "type", foreground: "b392f0" },
    { token: "type.identifier", foreground: "b392f0" },
    { token: "predefined", foreground: "c8e1ff" },
    { token: "identifier", foreground: "e1e4e8" },
    { token: "delimiter", foreground: "e1e4e8" },
    { token: "delimiter.bracket", foreground: "e1e4e8" },
    { token: "delimiter.parenthesis", foreground: "e1e4e8" },
    { token: "delimiter.square", foreground: "e1e4e8" },
    { token: "delimiter.angle", foreground: "e1e4e8" },
    { token: "operator", foreground: "f97583" },
    { token: "tag", foreground: "85e89d" },
    { token: "metatag", foreground: "85e89d" },
    { token: "metatag.content", foreground: "9ecbff" },
    { token: "attribute.name", foreground: "b392f0" },
    { token: "attribute.value", foreground: "9ecbff" },
    { token: "string.key.json", foreground: "79b8ff" },
    { token: "string.value.json", foreground: "9ecbff" },
    { token: "annotation", foreground: "b392f0" },
    { token: "regexp", foreground: "dbedff" },
  ],
  colors: {
    "editor.background": "#121212",
    "editor.foreground": "#e1e4e8",
    "editor.lineHighlightBackground": "#1A1A1A",
    "editor.selectionBackground": "#3392FF44",
    "editor.inactiveSelectionBackground": "#3392FF22",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#C6C6C6",
    "editorIndentGuide.background": "#2a2a2a",
    "editorIndentGuide.activeBackground": "#3a3a3a",
    "editorBracketMatch.background": "#17E5E633",
    "editorBracketMatch.border": "#17E5E600",
    "editorCursor.foreground": "#c8e1ff",
    "editor.findMatchBackground": "#ffd33d44",
    "editor.findMatchHighlightBackground": "#ffd33d22",
    "editorWhitespace.foreground": "#2f363d",
    "editorWidget.background": "#1f2428",
    "editorWidget.border": "#454545",
    "scrollbarSlider.background": "rgba(255,255,255,0.08)",
    "scrollbarSlider.hoverBackground": "rgba(255,255,255,0.15)",
    "scrollbarSlider.activeBackground": "rgba(255,255,255,0.20)",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.errorForeground": "#00000000",
    "editorOverviewRuler.warningForeground": "#00000000",
    "editorOverviewRuler.infoForeground": "#00000000",
    "editorOverviewRuler.findMatchForeground": "#00000000",
    "editorOverviewRuler.selectionHighlightForeground": "#00000000",
    "editorOverviewRuler.modifiedForeground": "#00000000",
    "editorOverviewRuler.addedForeground": "#00000000",
    "editorOverviewRuler.deletedForeground": "#00000000",
  },
};

/**
 * GitHub Light theme — sourced from monaco-themes (TextMate-based).
 */
export const lightTheme: IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", background: "ffffff", foreground: "24292e" },
    { token: "comment", foreground: "6a737d" },
    { token: "punctuation.definition.comment", foreground: "6a737d" },
    { token: "string.comment", foreground: "6a737d" },

    { token: "constant", foreground: "005cc5" },
    { token: "constant.language", foreground: "005cc5" },
    { token: "constant.numeric", foreground: "005cc5" },
    { token: "constant.character", foreground: "005cc5" },
    { token: "entity.name.constant", foreground: "005cc5" },
    { token: "variable.other.constant", foreground: "005cc5" },
    { token: "variable.language", foreground: "005cc5" },

    { token: "entity", foreground: "6f42c1" },
    { token: "entity.name", foreground: "6f42c1" },
    { token: "entity.name.function", foreground: "6f42c1" },
    { token: "entity.name.tag", foreground: "22863a" },
    { token: "entity.name.type", foreground: "6f42c1" },
    { token: "entity.name.class", foreground: "6f42c1" },
    { token: "entity.other.attribute-name", foreground: "6f42c1" },
    { token: "entity.other.inherited-class", foreground: "22863a" },

    { token: "variable.parameter.function", foreground: "24292e" },
    { token: "variable", foreground: "24292e" },
    { token: "variable.other", foreground: "24292e" },

    { token: "keyword", foreground: "d73a49" },
    { token: "keyword.control", foreground: "d73a49" },
    { token: "keyword.operator", foreground: "d73a49" },
    { token: "keyword.other", foreground: "d73a49" },
    { token: "storage", foreground: "d73a49" },
    { token: "storage.type", foreground: "d73a49" },
    { token: "storage.modifier", foreground: "d73a49" },

    { token: "string", foreground: "032f62" },
    { token: "string.regexp", foreground: "032f62" },
    { token: "string.escape", foreground: "005cc5" },

    { token: "support", foreground: "005cc5" },
    { token: "support.function", foreground: "005cc5" },
    { token: "support.class", foreground: "005cc5" },
    { token: "support.type", foreground: "005cc5" },
    { token: "support.constant", foreground: "005cc5" },
    { token: "support.variable", foreground: "005cc5" },

    { token: "meta.property-name", foreground: "005cc5" },

    { token: "invalid.broken", foreground: "b31d28", fontStyle: "italic" },
    { token: "invalid.deprecated", foreground: "b31d28", fontStyle: "italic" },
    { token: "invalid.illegal", foreground: "b31d28", fontStyle: "italic" },
    {
      token: "invalid.unimplemented",
      foreground: "b31d28",
      fontStyle: "italic",
    },

    { token: "markup.heading", foreground: "005cc5", fontStyle: "bold" },
    { token: "markup.bold", fontStyle: "bold" },
    { token: "markup.italic", fontStyle: "italic" },
    { token: "markup.inserted", foreground: "22863a" },
    { token: "markup.deleted", foreground: "b31d28" },
    { token: "markup.changed", foreground: "e36209" },
    { token: "markup.inline.raw", foreground: "032f62" },

    { token: "punctuation.definition.tag", foreground: "22863a" },

    // Monaco-specific tokens
    { token: "number", foreground: "005cc5" },
    { token: "number.hex", foreground: "005cc5" },
    { token: "type", foreground: "6f42c1" },
    { token: "type.identifier", foreground: "6f42c1" },
    { token: "predefined", foreground: "005cc5" },
    { token: "identifier", foreground: "24292e" },
    { token: "delimiter", foreground: "24292e" },
    { token: "delimiter.bracket", foreground: "24292e" },
    { token: "delimiter.parenthesis", foreground: "24292e" },
    { token: "delimiter.square", foreground: "24292e" },
    { token: "delimiter.angle", foreground: "24292e" },
    { token: "operator", foreground: "d73a49" },
    { token: "tag", foreground: "22863a" },
    { token: "metatag", foreground: "22863a" },
    { token: "metatag.content", foreground: "032f62" },
    { token: "attribute.name", foreground: "6f42c1" },
    { token: "attribute.value", foreground: "032f62" },
    { token: "string.key.json", foreground: "005cc5" },
    { token: "string.value.json", foreground: "032f62" },
    { token: "annotation", foreground: "6f42c1" },
    { token: "regexp", foreground: "032f62" },
  ],
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#24292e",
    "editor.lineHighlightBackground": "#F6F8FA",
    "editor.selectionBackground": "#0366d625",
    "editor.inactiveSelectionBackground": "#0366d611",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#24292e",
    "editorIndentGuide.background": "#eff2f5",
    "editorIndentGuide.activeBackground": "#d7dbe0",
    "editorBracketMatch.background": "#34d05833",
    "editorBracketMatch.border": "#34d05800",
    "editorCursor.foreground": "#044289",
    "editor.findMatchBackground": "#ffdf5d66",
    "editor.findMatchHighlightBackground": "#ffdf5d33",
    "editorWhitespace.foreground": "#d1d5da",
    "editorWidget.background": "#f6f8fa",
    "editorWidget.border": "#e1e4e8",
    "scrollbarSlider.background": "rgba(0,0,0,0.08)",
    "scrollbarSlider.hoverBackground": "rgba(0,0,0,0.15)",
    "scrollbarSlider.activeBackground": "rgba(0,0,0,0.20)",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.errorForeground": "#00000000",
    "editorOverviewRuler.warningForeground": "#00000000",
    "editorOverviewRuler.infoForeground": "#00000000",
    "editorOverviewRuler.findMatchForeground": "#00000000",
    "editorOverviewRuler.selectionHighlightForeground": "#00000000",
    "editorOverviewRuler.modifiedForeground": "#00000000",
    "editorOverviewRuler.addedForeground": "#00000000",
    "editorOverviewRuler.deletedForeground": "#00000000",
  },
};
